default_language_version: python312
default_stages:
  - "pre-commit"
default_install_hook_types:
  - "pre-commit"
  - "commit-msg"
  - "post-checkout"
  - "post-merge"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-ast
      - id: end-of-file-fixer
      - id: fix-end-of-line: --fix=lf
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v1.0.0
    hooks:
      - id: ruff-format
      - id: ruff
