ci:
    autofix_commit_msg: |
        style(pre-commit.ci): auto fixes from pre-commit hooks

        for more information, see https://pre-commit.ci
    autoupdate_branch: ''
    autoupdate_commit_msg: 'ci(deps): pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip:
      - "ruff"
defaultk_language_version:
  python: python3.11
default_stages:
  - "pre-commit"
default_install_hook_types:
  - "pre-commit"
  - "commit-msg"
  - "post-checkout"
  - "post-merge"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-ast
      - id: end-of-file-fixer
        exclude: '(^.+\.(md|txt|css)$)|(^LICENSE$)|(^(.github|\.vscode|addon/doc|addon/locale)/)'
      - id: mixed-line-ending
        exclude: '(^.+\.(md|txt|css)$)|(^LICENSE$)|(^(.github|\.vscode|addon/doc|addon/locale)/)'
        args:
          - "--fix=lf"
      - id: check-toml
      - id: trailing-whitespace
        exclude: '(^.+\.(md|txt|css)$)|(^LICENSE$)|(^(.github|\.vscode|addon/doc|addon/locale)/)'
      - id: check-case-conflict
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.3.1"
    hooks:
      - id: ruff-format
      - id: ruff
