[tool.ruff]
src = ["addon"]
respect-gitignore = true
unsafe-fixes = false
target-version = "py311"
extend-exclude = [".github/", "*.json", "*.ini", "LICENSE", "*.css", "*.po", ".vscode/", "*.md", "site_scons/"]

[tool.ruff.format]
indent-style = "tab"
line-ending = "lf"
quote-style = "preserve"
skip-magic-trailing-comma = true

[tool.ruff.lint]
ignore-init-module-imports = true
ignore = ["F821"]
