name: Check PR branch

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  check-pr-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check author
        uses: actions/github-script@v7
        if: ${{ github.event.pull_request.user.login != 'Nael-Sayegh' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hello, Thank you for your contribution to Scanvox for NVDA. Pull requests should be made on the target branch `dev`. Please change the target branch and rebase your modifications onto it.'
            })