name: pull_request

permissions:
  pull-requests: write


on:
  issue_comment:
    types: [created]


jobs:
  scons:
  if: "!contains(github.event.pull_request.labels.*.name, 'notForAddon')"
    uses: Nael-Sayegh/github-action/.github/workflows/pull_request.yml@main
    secrets: inherit