name: scons
on: 
  push:
    tags: 
      - '*'

jobs:
  scons: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install scons
        run: pip install scons
      - name: install markdown
        run: pip install markdown
      - name: Install gettext
        run: sudo apt-get install gettext
      - name: Generating Addon
        run: scons
      - name: get the last tag
        id: get-latest-tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Upload the nvda add-on 
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.USER_SFTP }}
          server: ${{ secrets.HOST_SFTP }}
          port: ${{ secrets.PORT_SFTP }}
          local_path: './*.nvda-addon'
          remote_path: '/var/www/nvda/addons/addons/scanvox'
          sftp_only: true
          password: ${{ secrets.MDP_SFTP }}
      - name: add file in release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.nvda-addon
          body_path: changelog.md